version: 0.2

env:
  variables:
    ENVIRONMENT: dev
    TF_IN_AUTOMATION: 1
    TERRAFORM_VERSION: 1.3.0
    BASE_PATH: terraform/elastic

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - ./${BASE_PATH}/install.sh
  pre_build:
    commands:
      - echo Starting pre-build...
      - ./${BASE_PATH}/prebuild.sh
  build:
    commands:
      - ./${BASE_PATH}/test.sh
  post_build:
    commands:
      - echo Test Performed completed on `date`
