version: 0.2

env:
  variables:
    ENVIRONMENT: dev
    TERRAFORM_VERSION: 1.8.5
    BASE_PATH: terraform/elastic

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip && mv terraform /usr/bin
      - rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - terraform --version
