version: 0.2

env:
  variables:
    ENVIRONMENT: dev
    TERRAFORM_VERSION: 1.8.5
    BASE_PATH: terraform/elastic

phases:
  install:
    commands:
      - set -e
      - eval $(ssh-agent)
      - echo "SSH_AUTH_SOCK ${SSH_AUTH_SOCK}"
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      - cd /tmp
      - echo "Installing Terraform"
      - curl -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip -o terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - mv terraform /usr/bin/terraform
      - rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - terraform --version
  pre_build:
    commands:
      - echo "Starting pre-build..."
      - cd ./${BASE_PATH}
      - terraform init
      - terraform validate
  build:
    commands:
      - echo "Starting build..."
      - terraform plan
